spring:
  profiles:
    active: local
  application:
    name: core-query-server
  redis:
    host : 127.0.0.1
    port : 36
    password : 123
my:
  config:
    savePath:
server:
  port: 8089

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-test-zhu
      address:  # 填充地址，假设执行器运行在本地
      ip: 127.0.0.1  # 填充本地IP，确保它与address配置一致
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1




